[opcache]
; Основные настройки включения
opcache.enable=0
opcache.enable_cli=0

; Производительность: Отключаем проверку файлов
; ВАЖНО: При деплое нужно будет сбрасывать кеш через opcache_reset() или перезапуск fpm
opcache.validate_timestamps=1
opcache.revalidate_freq=0

; Память
opcache.memory_consumption=256
opcache.interned_strings_buffer=32
opcache.max_wasted_percentage=5

; Лимиты файлов
; Число должно быть простым и больше, чем общее количество файлов в проекте
opcache.max_accelerated_files=32000

; Оптимизация выполнения
opcache.save_comments=1
opcache.fast_shutdown=0 ; (Для PHP 7.2+ эта опция игнорируется, можно удалить)

; Preloading
; opcache.file_cache=/var/www/writable/cache
; opcache.preload=/var/www/preload.php
; opcache.preload_user=www-data
