; включаем логирование ошибок
log_errors = on
; отправляем ошибки в stderr контейнера
error_log = /proc/self/fd/2
; error_log = /tmp/php/fpm.log
; показывать ошибки в браузере не нужно
; display_errors = Off
; уровень ошибок — все
error_reporting = E_ALL

expose_php = off
upload_max_filesize = 100M
post_max_size = 100M
memory_limit = 512M
max_execution_time = 60
max_input_time = 60
