/*
  Удаление временного BPK-слоя из C:\Firebird\tm07_bench.fdb
  (TM07_* таблицы стенда остаются)

  IBExpert: Execute (F9) → Commit
  Порядок важен из-за зависимостей.
*/

DROP TABLE BPKDOC;
DROP TABLE BPKEVENTS;
DROP TABLE BPK;
DROP TABLE SECUSER;
DROP TABLE STAND;
DROP TABLE DOCTYPEDICT;
DROP TABLE REGISTERTABLE;
DROP TABLE BPKEVENTSTATEDICT;
DROP TABLE BPKEVENTTYPEDICT;
DROP TABLE BPKTYPEDICT;

DROP GENERATOR GEN_BPKDOC_ID;
DROP GENERATOR GEN_BPKEVENTS_ID;
DROP GENERATOR GEN_BPK_ID;
DROP GENERATOR GEN_BPKEVENTSTATEDICT_ID;
DROP GENERATOR GEN_BPKEVENTTYPEDICT_ID;
DROP GENERATOR GEN_BPKTYPEDICT_ID;
