/*
  =====================================================================
  tm07_bench.fdb — подготовка BPK / BPKEVENTS (локально, как bpek_test)
  =====================================================================

  База:     C:\Firebird\tm07_bench.fdb
  Dialect:  3, charset UTF8
  Логин:    SYSDBA / masterkey

  Перед первым запуском (один раз):
    database/bpek_tm07_bench_schema.ibexpert.sql

  IBExpert: подключиться к C:\Firebird\tm07_bench.fdb
            → Script Executive → Execute (F9) → Commit

  Скрипт идемпотентный — можно выполнять повторно.
  TM07_* таблицы стенда не затрагиваются.
*/

/* ---------- 1) Справочники ---------- */

INSERT INTO BPKEVENTSTATEDICT (ID, NAME)
SELECT 0, 'Годен' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM BPKEVENTSTATEDICT WHERE ID = 0);

INSERT INTO BPKEVENTSTATEDICT (ID, NAME)
SELECT 1, 'Не годен' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM BPKEVENTSTATEDICT WHERE ID = 1);

INSERT INTO BPKEVENTSTATEDICT (ID, NAME)
SELECT 2, 'Не определено' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM BPKEVENTSTATEDICT WHERE ID = 2);

INSERT INTO BPKEVENTSTATEDICT (ID, NAME)
SELECT 3, 'ОК' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM BPKEVENTSTATEDICT WHERE ID = 3);

INSERT INTO BPKEVENTSTATEDICT (ID, NAME)
SELECT 4, 'Ошибка' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM BPKEVENTSTATEDICT WHERE ID = 4);

INSERT INTO BPKEVENTSTATEDICT (ID, NAME)
SELECT 5, 'Исправлено' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM BPKEVENTSTATEDICT WHERE ID = 5);

INSERT INTO REGISTERTABLE (ID, NAME)
SELECT 0, 'NO_TABLE' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM REGISTERTABLE WHERE ID = 0);

INSERT INTO REGISTERTABLE (ID, NAME)
SELECT 1, 'BOARDS' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM REGISTERTABLE WHERE ID = 1);

INSERT INTO REGISTERTABLE (ID, NAME)
SELECT 2, 'BPK' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM REGISTERTABLE WHERE ID = 2);

INSERT INTO DOCTYPEDICT (ID, NAME)
SELECT 1, 'Паспорт изделия' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM DOCTYPEDICT WHERE ID = 1);

INSERT INTO DOCTYPEDICT (ID, NAME)
SELECT 2, 'Протокол поверки' FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM DOCTYPEDICT WHERE ID = 2);

INSERT INTO BPKTYPEDICT (ID, NAME, LEGALNAME, BOARDS_BITS, PREFIX_NEW)
SELECT 37, 'TM07', 'Корректор объема газа ТМ-07', 128, '300'
FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM BPKTYPEDICT WHERE ID = 37);

INSERT INTO BPKTYPEDICT (ID, NAME, LEGALNAME, BOARDS_BITS, PREFIX_NEW)
SELECT 38, 'PCTM07', 'Промышленный комплекс ТМ-07', 128, '400'
FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM BPKTYPEDICT WHERE ID = 38);

INSERT INTO STAND (STANDID, STANDNUM, STANDNAMEID, COMMENT)
SELECT 0, '0', 1, 'Безадресное раб. место'
FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM STAND WHERE STANDID = 0);

INSERT INTO STAND (STANDID, STANDNUM, STANDNAMEID, COMMENT)
SELECT 1, '0', 2, 'Стенд параметризации ТМ-07 (локальный bench)'
FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM STAND WHERE STANDID = 1);

INSERT INTO SECUSER (ID, SAMACCOUNTNAME, FNAME, LNAME, FULLNAME, ROLE, STANDID, ENABLED)
SELECT 1, 'bench', 'Стенд', 'ТМ-07', 'Стенд ТМ-07 (bench)', 6, 1, 1
FROM RDB$DATABASE
WHERE NOT EXISTS (SELECT 1 FROM SECUSER WHERE ID = 1);


/* ---------- 2) Типы событий ТМ-07 ---------- */

INSERT INTO BPKEVENTTYPEDICT (ID, NAME)
SELECT GEN_ID(GEN_BPKEVENTTYPEDICT_ID, 1), 'ТМ-07: выдача серийного номера'
FROM RDB$DATABASE
WHERE NOT EXISTS (
  SELECT 1 FROM BPKEVENTTYPEDICT WHERE NAME = 'ТМ-07: выдача серийного номера'
);

INSERT INTO BPKEVENTTYPEDICT (ID, NAME)
SELECT GEN_ID(GEN_BPKEVENTTYPEDICT_ID, 1), 'ТМ-07: подтверждение сборки'
FROM RDB$DATABASE
WHERE NOT EXISTS (
  SELECT 1 FROM BPKEVENTTYPEDICT WHERE NAME = 'ТМ-07: подтверждение сборки'
);

INSERT INTO BPKEVENTTYPEDICT (ID, NAME)
SELECT GEN_ID(GEN_BPKEVENTTYPEDICT_ID, 1), 'ТМ-07: начало параметризации'
FROM RDB$DATABASE
WHERE NOT EXISTS (
  SELECT 1 FROM BPKEVENTTYPEDICT WHERE NAME = 'ТМ-07: начало параметризации'
);

INSERT INTO BPKEVENTTYPEDICT (ID, NAME)
SELECT GEN_ID(GEN_BPKEVENTTYPEDICT_ID, 1), 'ТМ-07: параметризация завершена'
FROM RDB$DATABASE
WHERE NOT EXISTS (
  SELECT 1 FROM BPKEVENTTYPEDICT WHERE NAME = 'ТМ-07: параметризация завершена'
);

INSERT INTO BPKEVENTTYPEDICT (ID, NAME)
SELECT GEN_ID(GEN_BPKEVENTTYPEDICT_ID, 1), 'ТМ-07: сверка после записи'
FROM RDB$DATABASE
WHERE NOT EXISTS (
  SELECT 1 FROM BPKEVENTTYPEDICT WHERE NAME = 'ТМ-07: сверка после записи'
);

INSERT INTO BPKEVENTTYPEDICT (ID, NAME)
SELECT GEN_ID(GEN_BPKEVENTTYPEDICT_ID, 1), 'ТМ-07: печать шильдика'
FROM RDB$DATABASE
WHERE NOT EXISTS (
  SELECT 1 FROM BPKEVENTTYPEDICT WHERE NAME = 'ТМ-07: печать шильдика'
);

INSERT INTO BPKEVENTTYPEDICT (ID, NAME)
SELECT GEN_ID(GEN_BPKEVENTTYPEDICT_ID, 1), 'ТМ-07: формирование паспорта'
FROM RDB$DATABASE
WHERE NOT EXISTS (
  SELECT 1 FROM BPKEVENTTYPEDICT WHERE NAME = 'ТМ-07: формирование паспорта'
);

INSERT INTO BPKEVENTTYPEDICT (ID, NAME)
SELECT GEN_ID(GEN_BPKEVENTTYPEDICT_ID, 1), 'ТМ-07: ошибка параметризации'
FROM RDB$DATABASE
WHERE NOT EXISTS (
  SELECT 1 FROM BPKEVENTTYPEDICT WHERE NAME = 'ТМ-07: ошибка параметризации'
);


/* ---------- 3) Проверка ---------- */

SELECT ID, NAME, LEGALNAME, PREFIX_NEW, BOARDS_BITS
FROM BPKTYPEDICT
WHERE ID IN (37, 38)
ORDER BY ID;

SELECT ID, NAME
FROM BPKEVENTTYPEDICT
WHERE NAME STARTING WITH 'ТМ-07:'
ORDER BY ID;

SELECT ID, NAME FROM BPKEVENTSTATEDICT ORDER BY ID;

SELECT ID, NAME FROM REGISTERTABLE WHERE ID = 2;

SELECT ID, NAME FROM DOCTYPEDICT ORDER BY ID;

SELECT ID, SAMACCOUNTNAME, FULLNAME, STANDID FROM SECUSER ORDER BY ID;

SELECT STANDID, COMMENT FROM STAND ORDER BY STANDID;


/*
  ========== ПРИМЕРЫ ЗАПИСИ (локальный bench) ==========

  SELECT ID FROM BPKEVENTTYPEDICT
  WHERE NAME = 'ТМ-07: параметризация завершена';

  INSERT INTO BPK (ID, SERIAL, TYPE, CURRENT_HW_VER, STATE_CURR_ID)
  VALUES (GEN_ID(GEN_BPK_ID, 1), '3002608005', 37, '128', 2);

  INSERT INTO BPKEVENTS (
    ID, EVENTTYPEID, EVENTDATE, EVENTSTATE,
    BPKID, USERID, STANDID, TABLEID, OBJECTID, COMMENT
  ) VALUES (
    GEN_ID(GEN_BPKEVENTS_ID, 1),
    :EVENTTYPEID,
    CURRENT_TIMESTAMP,
    0,
    :BPKID,
    1,
    1,
    2,
    :BPKID,
    '{"order":"TM00-000712","scope":"corrector","template":"RVG G40","ok":85,"fail":0}'
  );

  UPDATE BPK SET LAST_EVENT_ID = :EVENTID, STATE_CURR_ID = 0 WHERE ID = :BPKID;

  Откат BPK-слоя: bpek_tm07_bench_drop.ibexpert.sql
*/
