/*
  Drop TM07 objects before re-install (isql or IBExpert Script Executive).
*/

DROP TABLE TM07_CYCLE_PROGRESS;
DROP TABLE TM07_BENCH_EVENT;
DROP TABLE TM07_SERIAL_ISSUED;
DROP TABLE TM07_SERIAL_COUNTER;
DROP TABLE TM07_EVENT_TYPE;
DROP TABLE TM07_OPERATOR;
DROP TABLE TM07_WORKSTATION;

DROP GENERATOR GEN_TM07_BENCH_EVENT_ID;
DROP GENERATOR GEN_TM07_SERIAL_ISSUED_ID;
DROP GENERATOR GEN_TM07_EVENT_TYPE_ID;
DROP GENERATOR GEN_TM07_OPERATOR_ID;
DROP GENERATOR GEN_TM07_WORKSTATION_ID;
