-- TM-07 bench schema — PostgreSQL 16+
-- SoT for manual psql / docker init. PHP also ensure-creates via db_bench.php.
-- Identifiers unquoted → stored lowercase; PDO ATTR_CASE=UPPER for PHP rows.

CREATE TABLE IF NOT EXISTS tm07_workstation (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64) NOT NULL UNIQUE,
    name            VARCHAR(128),
    hostname        VARCHAR(128),
    client_fingerprint VARCHAR(64),
    config_json     TEXT,
    is_active       SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS tm07_operator (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login           VARCHAR(64) NOT NULL UNIQUE,
    display_name    VARCHAR(128) NOT NULL,
    last_name       VARCHAR(64),
    first_name      VARCHAR(64),
    pin_hash        VARCHAR(255),
    is_active       SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tm07_event_type (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64) NOT NULL UNIQUE,
    name            VARCHAR(256) NOT NULL,
    stage           VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS tm07_serial_counter (
    prefix          CHAR(3) NOT NULL,
    month_key       CHAR(4) NOT NULL,
    last_seq        INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (prefix, month_key)
);

CREATE TABLE IF NOT EXISTS tm07_serial_issued (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial          CHAR(10) NOT NULL UNIQUE,
    kind            VARCHAR(16) NOT NULL,
    prefix          CHAR(3) NOT NULL,
    month_key       CHAR(4) NOT NULL,
    seq             INTEGER NOT NULL,
    operator_id     INTEGER REFERENCES tm07_operator(id),
    workstation_id  INTEGER REFERENCES tm07_workstation(id),
    order_number    VARCHAR(64),
    payload         TEXT,
    issued_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_si_issued_at ON tm07_serial_issued (issued_at);
CREATE INDEX IF NOT EXISTS idx_si_order_kind ON tm07_serial_issued (order_number, kind);

CREATE TABLE IF NOT EXISTS tm07_bench_event (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type_id   INTEGER NOT NULL REFERENCES tm07_event_type(id),
    event_state     VARCHAR(32) NOT NULL DEFAULT 'done',
    serial_corrector CHAR(10),
    serial_complex  CHAR(10),
    stage           VARCHAR(32),
    operator_id     INTEGER REFERENCES tm07_operator(id),
    workstation_id  INTEGER REFERENCES tm07_workstation(id),
    payload         TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_be_serial_c ON tm07_bench_event (serial_corrector, created_at);
CREATE INDEX IF NOT EXISTS idx_be_serial_x ON tm07_bench_event (serial_complex, created_at);
CREATE INDEX IF NOT EXISTS idx_be_created ON tm07_bench_event (created_at);

CREATE TABLE IF NOT EXISTS tm07_bench_session (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number    VARCHAR(64) NOT NULL,
    order_status    VARCHAR(128),
    operator_id     INTEGER REFERENCES tm07_operator(id),
    workstation_id  INTEGER NOT NULL REFERENCES tm07_workstation(id),
    order_payload   TEXT,
    state           VARCHAR(16) NOT NULL DEFAULT 'active',
    session_stage   VARCHAR(32) NOT NULL DEFAULT 'assembly',
    serial_corrector VARCHAR(32),
    assembly_confirmed_at TIMESTAMPTZ,
    opened_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_bs_ws_active ON tm07_bench_session (workstation_id, state);

CREATE TABLE IF NOT EXISTS tm07_cycle_progress (
    serial_number   VARCHAR(40) NOT NULL PRIMARY KEY,
    phase_states    TEXT NOT NULL,
    next_phase_index INTEGER NOT NULL DEFAULT 0,
    last_phase      VARCHAR(64),
    cycle_status    VARCHAR(64),
    report_summary  TEXT,
    operator_id     INTEGER,
    workstation_id  INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Привязка датчиков (DA/DT/DD/TT) к S/N корректора: все sensor_serial уникальны.
CREATE TABLE IF NOT EXISTS tm07_corrector_sensor (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_corrector CHAR(10) NOT NULL,
    channel          VARCHAR(4) NOT NULL,
    sensor_serial    VARCHAR(64) NOT NULL,
    qr_raw           TEXT,
    session_id       INTEGER REFERENCES tm07_bench_session(id),
    order_number     VARCHAR(64),
    operator_id      INTEGER REFERENCES tm07_operator(id),
    workstation_id   INTEGER REFERENCES tm07_workstation(id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cs_sensor_serial UNIQUE (sensor_serial),
    CONSTRAINT uq_cs_corrector_channel UNIQUE (serial_corrector, channel),
    CONSTRAINT chk_cs_channel CHECK (channel IN ('DA', 'DT', 'DD', 'TT'))
);

CREATE INDEX IF NOT EXISTS idx_cs_corrector ON tm07_corrector_sensor (serial_corrector);
CREATE INDEX IF NOT EXISTS idx_cs_channel ON tm07_corrector_sensor (channel, sensor_serial);

INSERT INTO tm07_event_type (code, name, stage) VALUES
    ('operator_login', 'Вход оператора', 'auth'),
    ('workstation_register', 'Регистрация рабочего места (ПК)', 'auth'),
    ('order_session_open', 'Открытие сессии заказа', 'order'),
    ('order_session_close', 'Закрытие сессии заказа', 'order'),
    ('assembly_confirm', 'Подтверждение сборки корректора', 'assembly'),
    ('serial_corrector', 'Выдача S/N корректора', 'serial'),
    ('serial_complex', 'Выдача S/N комплекса', 'serial'),
    ('nameplate_print', 'Печать шильдика', 'serial'),
    ('sensor_bind', 'Привязка датчика к корректору', 'parametrization'),
    ('parametrization_start', 'Начало параметризации', 'parametrization'),
    ('parametrization_verify', 'Сверка после записи', 'parametrization'),
    ('parametrization_done', 'Параметризация завершена', 'parametrization'),
    ('passport_generate', 'Формирование паспорта', 'parametrization'),
    ('calibration_start', 'Начало калибровки', 'calibration'),
    ('calibration_done', 'Калибровка завершена', 'calibration'),
    ('calibration_phase', 'Этап калибровки', 'calibration')
ON CONFLICT (code) DO NOTHING;
