/*
  TM-07 bench schema — Firebird 2.5+ (GENERATOR + triggers).
  Create Database: SQL Dialect 3, Charset UTF8. Do not use SET SQL DIALECT in this script.
*/

/* --- TM07_WORKSTATION --- */
CREATE GENERATOR GEN_TM07_WORKSTATION_ID;

CREATE TABLE TM07_WORKSTATION (
    ID          INTEGER NOT NULL PRIMARY KEY,
    CODE        VARCHAR(64) NOT NULL UNIQUE,
    NAME        VARCHAR(128),
    HOSTNAME    VARCHAR(128),
    IS_ACTIVE   SMALLINT DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

SET TERM ^ ;
CREATE TRIGGER BI_TM07_WORKSTATION FOR TM07_WORKSTATION
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_TM07_WORKSTATION_ID, 1);
END^
SET TERM ; ^

/* --- TM07_OPERATOR --- */
CREATE GENERATOR GEN_TM07_OPERATOR_ID;

CREATE TABLE TM07_OPERATOR (
    ID           INTEGER NOT NULL PRIMARY KEY,
    LOGIN        VARCHAR(64) NOT NULL UNIQUE,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    IS_ACTIVE    SMALLINT DEFAULT 1 NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

SET TERM ^ ;
CREATE TRIGGER BI_TM07_OPERATOR FOR TM07_OPERATOR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_TM07_OPERATOR_ID, 1);
END^
SET TERM ; ^

/* --- TM07_EVENT_TYPE --- */
CREATE GENERATOR GEN_TM07_EVENT_TYPE_ID;

CREATE TABLE TM07_EVENT_TYPE (
    ID          INTEGER NOT NULL PRIMARY KEY,
    CODE        VARCHAR(64) NOT NULL UNIQUE,
    NAME        VARCHAR(256) NOT NULL,
    STAGE       VARCHAR(32)
);

SET TERM ^ ;
CREATE TRIGGER BI_TM07_EVENT_TYPE FOR TM07_EVENT_TYPE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_TM07_EVENT_TYPE_ID, 1);
END^
SET TERM ; ^

INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('operator_login', 'Вход оператора', 'auth');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('workstation_register', 'Регистрация рабочего места', 'auth');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('order_session_open', 'Открытие сессии заказа', 'order');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('order_session_close', 'Закрытие сессии заказа', 'order');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('assembly_confirm', 'Подтверждение сборки корректора', 'assembly');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('serial_corrector', 'Выдача S/N корректора', 'serial');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('serial_complex', 'Выдача S/N комплекса', 'serial');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('nameplate_print', 'Печать шильдика', 'serial');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('parametrization_start', 'Начало параметризации', 'parametrization');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('parametrization_verify', 'Сверка после записи', 'parametrization');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('parametrization_done', 'Параметризация завершена', 'parametrization');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('passport_generate', 'Формирование паспорта', 'parametrization');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('calibration_start', 'Начало калибровки', 'calibration');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('calibration_done', 'Калибровка завершена', 'calibration');
INSERT INTO TM07_EVENT_TYPE (CODE, NAME, STAGE) VALUES ('calibration_phase', 'Этап калибровки', 'calibration');

/* --- TM07_SERIAL_COUNTER --- */
CREATE TABLE TM07_SERIAL_COUNTER (
    PREFIX     CHAR(3) NOT NULL,
    MONTH_KEY  CHAR(4) NOT NULL,
    LAST_SEQ   INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY (PREFIX, MONTH_KEY)
);

/* --- TM07_SERIAL_ISSUED --- */
CREATE GENERATOR GEN_TM07_SERIAL_ISSUED_ID;

CREATE TABLE TM07_SERIAL_ISSUED (
    ID               INTEGER NOT NULL PRIMARY KEY,
    SERIAL           CHAR(10) NOT NULL UNIQUE,
    KIND             VARCHAR(16) NOT NULL,
    PREFIX           CHAR(3) NOT NULL,
    MONTH_KEY        CHAR(4) NOT NULL,
    SEQ              INTEGER NOT NULL,
    OPERATOR_ID      INTEGER,
    WORKSTATION_ID   INTEGER,
    ORDER_NUMBER     VARCHAR(64),
    PAYLOAD          BLOB SUB_TYPE TEXT,
    ISSUED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_SI_OP FOREIGN KEY (OPERATOR_ID) REFERENCES TM07_OPERATOR(ID),
    CONSTRAINT FK_SI_WS FOREIGN KEY (WORKSTATION_ID) REFERENCES TM07_WORKSTATION(ID)
);

SET TERM ^ ;
CREATE TRIGGER BI_TM07_SERIAL_ISSUED FOR TM07_SERIAL_ISSUED
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_TM07_SERIAL_ISSUED_ID, 1);
END^
SET TERM ; ^

CREATE INDEX IDX_SI_ISSUED_AT ON TM07_SERIAL_ISSUED (ISSUED_AT);

/* --- TM07_BENCH_EVENT --- */
CREATE GENERATOR GEN_TM07_BENCH_EVENT_ID;

CREATE TABLE TM07_BENCH_EVENT (
    ID               INTEGER NOT NULL PRIMARY KEY,
    EVENT_TYPE_ID    INTEGER NOT NULL,
    EVENT_STATE      VARCHAR(32) DEFAULT 'done' NOT NULL,
    SERIAL_CORRECTOR CHAR(10),
    SERIAL_COMPLEX   CHAR(10),
    STAGE            VARCHAR(32),
    OPERATOR_ID      INTEGER,
    WORKSTATION_ID   INTEGER,
    PAYLOAD          BLOB SUB_TYPE TEXT,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_BE_TYPE FOREIGN KEY (EVENT_TYPE_ID) REFERENCES TM07_EVENT_TYPE(ID),
    CONSTRAINT FK_BE_OP FOREIGN KEY (OPERATOR_ID) REFERENCES TM07_OPERATOR(ID),
    CONSTRAINT FK_BE_WS FOREIGN KEY (WORKSTATION_ID) REFERENCES TM07_WORKSTATION(ID)
);

SET TERM ^ ;
CREATE TRIGGER BI_TM07_BENCH_EVENT FOR TM07_BENCH_EVENT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_TM07_BENCH_EVENT_ID, 1);
END^
SET TERM ; ^

CREATE INDEX IDX_BE_SERIAL_C ON TM07_BENCH_EVENT (SERIAL_CORRECTOR, CREATED_AT);
CREATE INDEX IDX_BE_SERIAL_X ON TM07_BENCH_EVENT (SERIAL_COMPLEX, CREATED_AT);
CREATE INDEX IDX_BE_CREATED ON TM07_BENCH_EVENT (CREATED_AT);

/* --- TM07_CYCLE_PROGRESS --- */
CREATE TABLE TM07_CYCLE_PROGRESS (
    SERIAL_NUMBER      VARCHAR(40) NOT NULL PRIMARY KEY,
    PHASE_STATES       BLOB SUB_TYPE TEXT NOT NULL,
    NEXT_PHASE_INDEX   INTEGER DEFAULT 0 NOT NULL,
    LAST_PHASE         VARCHAR(64),
    CYCLE_STATUS       VARCHAR(64),
    REPORT_SUMMARY     BLOB SUB_TYPE TEXT,
    OPERATOR_ID        INTEGER,
    WORKSTATION_ID     INTEGER,
    CREATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMIT;
